# Yarn v4 Configuration for DangerPrep Turborepo

# Use node_modules linker for better compatibility with Docker and existing tooling
nodeLinker: node-modules

# FontAwesome Pro Kit Configuration
# Configure access to FontAwesome Pro packages and kits
# Set FONTAWESOME_NPM_AUTH_TOKEN environment variable before running yarn
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"

