services:
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount secrets as files for enhanced security
      - ${INSTALL_ROOT}/secrets/watchtower/api_token:/run/secrets/watchtower_api_token:ro
      - ${INSTALL_ROOT}/secrets/watchtower/email_password:/run/secrets/email_password:ro
      - ${INSTALL_ROOT}/secrets/watchtower/gotify_token:/run/secrets/gotify_token:ro
    env_file:
      - compose.env
    user: "1337:1337"
    environment:
      # Use file-based secrets for enhanced security
      - WATCHTOWER_HTTP_API_TOKEN_FILE=/run/secrets/watchtower_api_token
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD_FILE=/run/secrets/email_password
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN_FILE=/run/secrets/gotify_token
    command: --interval 86400 --cleanup --label-enable
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - watchtower
    healthcheck:
      test: ["CMD", "pgrep", "-f", "watchtower"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  watchtower:
    driver: bridge
