services:
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - compose.env
    command: --interval 86400 --cleanup --label-enable
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - watchtower
    healthcheck:
      test: ["CMD", "pgrep", "-f", "watchtower"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  watchtower:
    driver: bridge
