services:
  onedev:
    image: 1dev/server:latest
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /data/onedev:/opt/onedev
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount secrets as files for enhanced security
      - ${INSTALL_ROOT}/secrets/onedev/db_password:/run/secrets/db_password:ro
    env_file:
      - compose.env
    user: "1337:1337"
    environment:
      # Database configuration
      - hibernate_dialect=io.onedev.server.persistence.PostgreSQLDialect
      - hibernate_connection_driver_class=org.postgresql.Driver
      - hibernate_connection_url=jdbc:postgresql://postgres:5432/onedev
      - hibernate_connection_username=onedev
      - hibernate_connection_password=${POSTGRES_PASSWORD}
      
      # Server configuration
      - http_port=6610
      - ssh_port=3022
      - cluster_port=5710
    ports:
      - "3022:3022"  # SSH port needs to be exposed for Git operations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onedev.rule=Host(`dev.danger`)"
      - "traefik.http.routers.onedev.entrypoints=websecure"
      - "traefik.http.routers.onedev.tls.certresolver=step-ca"
      - "traefik.http.services.onedev.loadbalancer.server.port=6610"

      # DNS registration
      - "dns.register=dev.danger"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
      - onedev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6610/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  postgres:
    image: postgres:15.4
    restart: unless-stopped
    volumes:
      - /data/onedev/postgres:/var/lib/postgresql/data
    env_file:
      - compose.env
    user: "1337:1337"
    environment:
      - POSTGRES_DB=onedev
      - POSTGRES_USER=onedev
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - onedev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onedev -d onedev"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  traefik:
    external: true
    name: traefik
  onedev:
    driver: bridge
