services:
  step-ca:
    image: smallstep/step-ca:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /data/step-ca:/home/step
    env_file:
      - compose.env
    user: "1337:1337"
    environment:
      # Override specific settings for DangerPrep
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_ACME=true
    labels:
      - "traefik.enable=true"
      
      # Main CA API
      - "traefik.http.routers.step-ca.rule=Host(`ca.danger`)"
      - "traefik.http.routers.step-ca.entrypoints=websecure"
      - "traefik.http.routers.step-ca.tls.certresolver=step-ca"
      - "traefik.http.services.step-ca.loadbalancer.server.port=9000"
      - "traefik.http.services.step-ca.loadbalancer.server.scheme=https"

      # DNS registration
      - "dns.register=ca.danger"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
      - step-ca
    healthcheck:
      test: ["CMD", "step", "ca", "health", "--ca-url", "https://localhost:9000", "--root", "/home/step/certs/root_ca.crt"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ca-download:
    build:
      context: ../../..
      dockerfile: docker/infrastructure/step-ca/Dockerfile
    restart: unless-stopped
    volumes:
      - /data/step-ca:/ca-data:ro
      - /data/cdn-assets:/cdn-assets
    env_file:
      - compose.env
    environment:
      # Override specific settings for ca-download service
      - CA_NAME=${DOCKER_STEPCA_INIT_NAME:-DangerPrep Internal CA}
      - CA_URL=https://ca.danger:9000
    user: "1337:1337"  # Use same UID as step-ca container
    labels:
      - "traefik.enable=true"

      # HTTP-only download service (no HTTPS required for initial setup)
      - "traefik.http.routers.ca-download.rule=Host(`root.danger`)"
      - "traefik.http.routers.ca-download.entrypoints=web"
      - "traefik.http.services.ca-download.loadbalancer.server.port=8080"

      # DNS registration
      - "dns.register=root.danger"

      # App registration for discovery
      - "app.register=true"
      - "app.name=Certificate Authority"
      - "app.description=SSL Certificate Management"
      - "app.icon=shield-check"
      - "app.category=Security"
      - "app.url=https://root.danger"
      - "app.version=1.0.0"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
      - step-ca
    depends_on:
      - step-ca
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  traefik:
    external: true
  step-ca:
    driver: bridge
