services:
  cdn:
    build: .
    restart: unless-stopped
    volumes:
      - ./assets:/usr/share/nginx/html/assets:ro
    env_file:
      - compose.env
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      
      # CDN service
      - "traefik.http.routers.cdn.rule=Host(`cdn.danger`)"
      - "traefik.http.routers.cdn.entrypoints=websecure"
      - "traefik.http.routers.cdn.tls.certresolver=step-ca"
      - "traefik.http.services.cdn.loadbalancer.server.port=80"

      # DNS registration
      - "dns.register=cdn.danger"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  traefik:
    external: true
