services:
  cdn:
    build:
      context: ../../..
      dockerfile: docker/infrastructure/cdn/Dockerfile
    restart: unless-stopped
    volumes:
      - ${INSTALL_ROOT}/data/cdn:/app/data
      - ./assets:/app/assets:ro
    env_file:
      - compose.env
    labels:
      - "traefik.enable=true"

      # CDN service
      - "traefik.http.routers.cdn.rule=Host(`cdn.danger`)"
      - "traefik.http.routers.cdn.entrypoints=websecure"
      - "traefik.http.routers.cdn.tls.certresolver=step-ca"
      - "traefik.http.services.cdn.loadbalancer.server.port=8080"

      # DNS registration
      - "dns.register=cdn.danger"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  traefik:
    external: true
