services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-data:/data
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    env_file:
      - compose.env
    environment:
      - LEGO_DISABLE_CNAME_SUPPORT=true
    labels:
      - "traefik.enable=true"

      # Dashboard - Internal (.danger domain with step-ca)
      - "traefik.http.routers.dashboard-internal.rule=Host(`traefik.danger`)"
      - "traefik.http.routers.dashboard-internal.entrypoints=websecure"
      - "traefik.http.routers.dashboard-internal.tls.certresolver=step-ca"
      - "traefik.http.routers.dashboard-internal.service=api@internal"
      - "traefik.http.routers.dashboard-internal.middlewares=auth"

      # Dashboard - External (.danger.diy domain with Let's Encrypt)
      - "traefik.http.routers.dashboard-external.rule=Host(`traefik.danger.diy`)"
      - "traefik.http.routers.dashboard-external.entrypoints=websecure"
      - "traefik.http.routers.dashboard-external.tls.certresolver=letsencrypt-cloudflare"
      - "traefik.http.routers.dashboard-external.service=api@internal"
      - "traefik.http.routers.dashboard-external.middlewares=auth"

      # Dashboard - External (.argos.surf domain with Let's Encrypt)
      - "traefik.http.routers.dashboard-argos.rule=Host(`traefik.argos.surf`)"
      - "traefik.http.routers.dashboard-argos.entrypoints=websecure"
      - "traefik.http.routers.dashboard-argos.tls.certresolver=letsencrypt-cloudflare"
      - "traefik.http.routers.dashboard-argos.service=api@internal"
      - "traefik.http.routers.dashboard-argos.middlewares=auth"

      # Basic auth middleware for dashboard
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_USERS}"

      # DNS registration
      - "dns.register=traefik"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      traefik: {}

volumes:
  traefik-data:
    driver: local

networks:
  traefik:
    name: traefik
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    labels:
      - "dangerprep.network=shared"
      - "dangerprep.description=Shared network for Traefik reverse proxy"

