services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${INSTALL_ROOT}/data/traefik:/data
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ${INSTALL_ROOT}/data/step-ca/certs/root_ca.crt:/etc/ssl/certs/step-ca-root.crt:ro
    env_file:
      - compose.env
    environment:
      - LEGO_CA_CERTIFICATES=/etc/ssl/certs/step-ca-root.crt
    labels:
      - "traefik.enable=true"

      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.danger`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=step-ca"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"

      # Basic auth middleware for dashboard
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_USERS}"

      # DNS registration
      - "dns.register=traefik.danger"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  traefik:
    driver: bridge
