services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/traefik:/data
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /data/step-ca/certs/root_ca.crt:/etc/ssl/certs/step-ca-root.crt:ro
    env_file:
      - compose.env
    user: "1337:1337"
    environment:
      - LEGO_CA_CERTIFICATES=/etc/ssl/certs/step-ca-root.crt
    labels:
      - "traefik.enable=true"

      # Dashboard - Internal (.danger domain with step-ca)
      - "traefik.http.routers.dashboard-internal.rule=Host(`traefik.danger`)"
      - "traefik.http.routers.dashboard-internal.entrypoints=websecure"
      - "traefik.http.routers.dashboard-internal.tls.certresolver=step-ca"
      - "traefik.http.routers.dashboard-internal.service=api@internal"
      - "traefik.http.routers.dashboard-internal.middlewares=auth"

      # Dashboard - External (.danger.diy domain with Let's Encrypt)
      - "traefik.http.routers.dashboard-external.rule=Host(`traefik.danger.diy`)"
      - "traefik.http.routers.dashboard-external.entrypoints=websecure"
      - "traefik.http.routers.dashboard-external.tls.certresolver=letsencrypt-cloudflare"
      - "traefik.http.routers.dashboard-external.service=api@internal"
      - "traefik.http.routers.dashboard-external.middlewares=auth"

      # Basic auth middleware for dashboard
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_USERS}"

      # DNS registration
      - "dns.register=traefik"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  traefik:
    external: true
    name: traefik
