api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    # Removed network constraint to support host-networked containers like RaspAP
    # network: traefik

  file:
    directory: /etc/traefik/dynamic
    watch: true

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  step-ca:
    acme:
      email: ${ACME_EMAIL}
      storage: /data/step-ca-acme.json
      caServer: https://step-ca-step-ca-1:9000/acme/acme/directory
      httpChallenge:
        entryPoint: web

  letsencrypt-cloudflare:
    acme:
      email: ${ACME_EMAIL}
      storage: /data/letsencrypt-acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

log:
  level: INFO

accessLog: {}

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
