services:
  sync-init:
    image: alpine:latest
    command: /bin/true
    restart: "no"
    networks:
      - traefik
    labels:
      - "dangerprep.service=sync"
      - "dangerprep.description=Sync initialization service"
#   offline-sync:
#     build:
#       context: ../../..
#       dockerfile: docker/sync/offline-sync/Dockerfile
#     restart: unless-stopped
#     privileged: true  # Required for USB device access and mounting
#     volumes:
#       - offline-sync-data:/app/data
#       - /content:/content
#       - ./config.yaml:/app/data/config.yaml:ro
#       - /dev:/dev  # Device access for USB detection
#       - /run/udev:/run/udev:ro  # udev for device information
#       - /sys:/sys:ro  # System information for device detection
#       # - /proc:/proc:ro  # Process information - removed to avoid read-only filesystem issues
#       - /run/dbus:/run/dbus  # D-Bus for udisks2 communication
#       - /var/run/dbus:/var/run/dbus  # Alternative D-Bus path
#     env_file:
#       - compose.env
#     labels:
#       # Watchtower
#       - "com.centurylinklabs.watchtower.enable=true"
#     networks:
#       - traefik
#     healthcheck:
#       test: ["CMD", "node", "dist/engine.js", "health", "--simple"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 30s

# volumes:
#   offline-sync-data:
#     driver: local

networks:
  traefik:
    external: true
