services:
  komga:
    image: gotson/komga:latest
    restart: unless-stopped
    volumes:
      - /data/komga/config:/config
      - /content/books:/books:ro
      - /content/comics:/comics:ro
      - /content/magazines:/magazines:ro
    env_file:
      - compose.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.komga.rule=Host(`komga.danger`)"
      - "traefik.http.routers.komga.entrypoints=websecure"
      - "traefik.http.routers.komga.tls.certresolver=step-ca"
      - "traefik.http.services.komga.loadbalancer.server.port=8080"

      # DNS registration
      - "dns.register=komga.danger"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  traefik:
    external: true
