services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "7359:7359/udp"  # Auto-discovery
      - "1900:1900/udp"  # DLNA
    volumes:
      - /data/jellyfin/config:/config
      - /data/jellyfin/cache:/cache
      - /content/movies:/media/movies:ro
      - /content/tv:/media/tv:ro
      - /content/webtv:/media/webtv:ro
      - /content/music:/media/music:ro
      - /content/audiobooks:/media/audiobooks:ro
    env_file:
      - compose.env
    user: "1337:1337"
    devices:
      - /dev/dri:/dev/dri  # Hardware transcoding for RK3588S
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.danger`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=step-ca"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

      # DNS registration
      - "dns.register=jellyfin.danger"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  traefik:
    external: true
    name: traefik
