services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "7359:7359/udp"  # Auto-discovery
      - "1900:1900/udp"  # DLNA
    volumes:
      - ${INSTALL_ROOT}/data/jellyfin/config:/config
      - ${INSTALL_ROOT}/data/jellyfin/cache:/cache
      - ${INSTALL_ROOT}/content/movies:/media/movies:ro
      - ${INSTALL_ROOT}/content/tv:/media/tv:ro
      - ${INSTALL_ROOT}/content/webtv:/media/webtv:ro
      - ${INSTALL_ROOT}/content/music:/media/music:ro
      - ${INSTALL_ROOT}/content/audiobooks:/media/audiobooks:ro
    env_file:
      - compose.env
    devices:
      - /dev/dri:/dev/dri  # Hardware transcoding for RK3588S
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.danger`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=cloudflare"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

      # DNS registration
      - "dns.register=jellyfin.danger"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

networks:
  traefik:
    external: true
