services:
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:latest
    restart: unless-stopped
    volumes:
      - /content/kiwix:/data:ro
    command: ["*.zim"]
    labels:
      - "traefik.enable=true"

      # Kiwix - Internal (.danger domain with step-ca)
      - "traefik.http.routers.kiwix-internal.rule=Host(`kiwix.danger`)"
      - "traefik.http.routers.kiwix-internal.entrypoints=websecure"
      - "traefik.http.routers.kiwix-internal.tls.certresolver=step-ca"
      - "traefik.http.routers.kiwix-internal.service=kiwix"

      # Kiwix - External (.danger.diy domain with Let's Encrypt)
      - "traefik.http.routers.kiwix-external.rule=Host(`kiwix.danger.diy`)"
      - "traefik.http.routers.kiwix-external.entrypoints=websecure"
      - "traefik.http.routers.kiwix-external.tls.certresolver=letsencrypt-cloudflare"
      - "traefik.http.routers.kiwix-external.service=kiwix"

      # Kiwix - External (.argos.surf domain with Let's Encrypt)
      - "traefik.http.routers.kiwix-argos.rule=Host(`kiwix.argos.diy`)"
      - "traefik.http.routers.kiwix-argos.entrypoints=websecure"
      - "traefik.http.routers.kiwix-argos.tls.certresolver=letsencrypt-cloudflare"
      - "traefik.http.routers.kiwix-argos.service=kiwix"

      # Service definition (shared by both routers)
      - "traefik.http.services.kiwix.loadbalancer.server.port=8080"

      # DNS registration
      - "dns.register=kiwix"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
      - kiwix

networks:
  traefik:
    external: true
    name: traefik
  kiwix:
    name: kiwix
    driver: bridge
