services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${INSTALL_ROOT}/data/arcane:/app/data
    env_file:
      - compose.env
    environment:
      - APP_ENV=production
      - PUID=1000
      - PGID=1000
      - PUBLIC_SESSION_SECRET=${PUBLIC_SESSION_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arcane.rule=Host(`docker.danger`)"
      - "traefik.http.routers.arcane.entrypoints=websecure"
      - "traefik.http.routers.arcane.tls.certresolver=step-ca"
      - "traefik.http.services.arcane.loadbalancer.server.port=3000"

      # DNS registration
      - "dns.register=docker.danger"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  traefik:
    external: true
