name: Package DangerPrep

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    # Allow manual triggering
  workflow_call:
    # Allow being called by other workflows

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download just binaries
        run: |
          cd lib/just
          ./download.sh --force
      
      - name: Download gum binaries
        run: |
          cd lib/gum
          ./download.sh --force
      
      - name: Get version information
        id: versions
        run: |
          just_version=$(cat lib/just/VERSION 2>/dev/null || echo "unknown")
          gum_version=$(cat lib/gum/VERSION 2>/dev/null || echo "unknown")

          echo "just_version=$just_version" >> $GITHUB_OUTPUT
          echo "gum_version=$gum_version" >> $GITHUB_OUTPUT

          # Create a package tag based on commit SHA
          package_tag="package-$(git rev-parse --short HEAD)"
          echo "package_tag=$package_tag" >> $GITHUB_OUTPUT
      
      - name: Create package
        run: |
          # Create a comprehensive package with all binaries and scripts
          mkdir -p dangerprep-package

          # Copy the entire repository structure
          rsync -av --exclude='.git' --exclude='dangerprep-package' . dangerprep-package/

          # Create package info
          cat > dangerprep-package/PACKAGE_INFO << EOF
          DangerPrep Package
          Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          Commit: $(git rev-parse HEAD)
          Branch: $(git rev-parse --abbrev-ref HEAD)

          Included Binaries:
          - Just: ${{ steps.versions.outputs.just_version }}
          - Gum: ${{ steps.versions.outputs.gum_version }}

          Installation:
          1. Extract this package
          2. Run: ./bootstrap.sh

          Or run the setup directly:
          ./scripts/setup/setup-dangerprep.sh
          EOF

          # Create the package archive
          tar -czf dangerprep-${{ steps.versions.outputs.package_tag }}.tar.gz dangerprep-package/
      
      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dangerprep-package-${{ steps.versions.outputs.package_tag }}
          path: dangerprep-${{ steps.versions.outputs.package_tag }}.tar.gz
          retention-days: 30
      
      - name: Create summary
        run: |
          echo "## DangerPrep Package Created" >> $GITHUB_STEP_SUMMARY
          echo "Package tag: ${{ steps.versions.outputs.package_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "Just version: ${{ steps.versions.outputs.just_version }}" >> $GITHUB_STEP_SUMMARY
          echo "Gum version: ${{ steps.versions.outputs.gum_version }}" >> $GITHUB_STEP_SUMMARY
          echo "Commit: $(git rev-parse HEAD)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Package Contents:" >> $GITHUB_STEP_SUMMARY
          echo "- Complete DangerPrep codebase" >> $GITHUB_STEP_SUMMARY
          echo "- Cross-platform just binaries" >> $GITHUB_STEP_SUMMARY
          echo "- Cross-platform gum binaries" >> $GITHUB_STEP_SUMMARY
          echo "- Bootstrap installation script" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Artifact:" >> $GITHUB_STEP_SUMMARY
          echo "- dangerprep-${{ steps.versions.outputs.package_tag }}.tar.gz" >> $GITHUB_STEP_SUMMARY
