name: Update Just Binaries

on:
  workflow_call:
    # Allow being called by other workflows

permissions:
  contents: read

jobs:
  update-just:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest just version
        id: latest
        run: |
          latest=$(curl -s https://api.github.com/repos/casey/just/releases/latest | jq -r '.tag_name')
          echo "version=$latest" >> $GITHUB_OUTPUT

      - name: Download just binaries
        run: |
          cd lib/just
          ./download.sh --force --version ${{ steps.latest.outputs.version }}

      - name: Upload just binaries artifact
        uses: actions/upload-artifact@v4
        with:
          name: just-binaries
          path: lib/just/just-*
          retention-days: 1

      - name: Create summary
        run: |
          echo "## Just Binaries Downloaded" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ steps.latest.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Available Platforms:" >> $GITHUB_STEP_SUMMARY
          echo "- linux-x86_64, linux-aarch64, linux-armv7, linux-arm" >> $GITHUB_STEP_SUMMARY
          echo "- darwin-x86_64, darwin-aarch64" >> $GITHUB_STEP_SUMMARY
          echo "- windows-x86_64, windows-aarch64" >> $GITHUB_STEP_SUMMARY
