name: Update Gum Binaries

on:
  workflow_call:
    # Allow being called by other workflows

permissions:
  contents: read

jobs:
  update-gum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest gum version
        id: latest
        run: |
          latest=$(curl -s https://api.github.com/repos/charmbracelet/gum/releases/latest | jq -r '.tag_name')
          echo "version=$latest" >> $GITHUB_OUTPUT

      - name: Download gum binary for Linux x86_64
        run: |
          cd lib/gum
          ./download.sh --force --version ${{ steps.latest.outputs.version }}

      - name: Upload gum binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: gum-binaries
          path: lib/gum/gum
          retention-days: 1

      - name: Create summary
        run: |
          echo "## Gum Binary Downloaded" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ steps.latest.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Platform: Linux x86_64 (GitHub Actions runner)" >> $GITHUB_STEP_SUMMARY
