name: Update Just Binaries

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering

permissions:
  contents: write

jobs:
  update-just:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get current version
        id: current
        run: |
          if [ -f lib/just/VERSION ]; then
            echo "version=$(cat lib/just/VERSION)" >> $GITHUB_OUTPUT
          else
            echo "version=" >> $GITHUB_OUTPUT
          fi
      
      - name: Get latest just version
        id: latest
        run: |
          latest=$(curl -s https://api.github.com/repos/casey/just/releases/latest | jq -r '.tag_name')
          echo "version=$latest" >> $GITHUB_OUTPUT
      
      - name: Compare versions
        id: compare
        run: |
          current="${{ steps.current.outputs.version }}"
          latest="${{ steps.latest.outputs.version }}"
          
          if [ "$current" != "$latest" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "Current version: $current"
            echo "Latest version: $latest"
            echo "Update needed!"
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
            echo "Already up to date: $current"
          fi
      
      - name: Download new just binaries
        if: steps.compare.outputs.update_needed == 'true'
        run: |
          cd lib/just
          ./download.sh --force --version ${{ steps.latest.outputs.version }}
      
      - name: Commit and push changes
        if: steps.compare.outputs.update_needed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lib/just/
          git commit -m "chore: update just binaries to ${{ steps.latest.outputs.version }}"
          git push
      
      - name: Create summary
        if: steps.compare.outputs.update_needed == 'true'
        run: |
          echo "## Just Binaries Updated" >> $GITHUB_STEP_SUMMARY
          echo "Updated from ${{ steps.current.outputs.version }} to ${{ steps.latest.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Downloaded Binaries:" >> $GITHUB_STEP_SUMMARY
          ls -la lib/just/just-* | awk '{print "- " $9 " (" $5 " bytes)"}' >> $GITHUB_STEP_SUMMARY
